/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.LaundryPerson;

import Business.Organization.AttendantOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LaundryWorkRequest;
import Business.WorkQueue.RoomEssentialsRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vidya
 */
public class LaundryWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LaundryWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Organization organization;
    private AttendantOrganization attendantOrganization;
    private UserAccount userAccount;
    private JPanel mainPanel;
    public LaundryWorkAreaJPanel(JPanel userProcessContainer,UserAccount userAccount,Organization organization,JPanel mainPanel) {
        initComponents();
        attendantOrganization=(AttendantOrganization)organization;
        this.userProcessContainer=userProcessContainer;
        this.userAccount=userAccount;
        this.mainPanel=mainPanel;
        populateTable();
    }

    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)laundryTable.getModel();
        
        model.setRowCount(0);
        try{
        for(WorkRequest request : attendantOrganization.getWorkQueue().getWorkRequestList()){
            if(request instanceof LaundryWorkRequest){
            Object[] row = new Object[7];
            row[0] = request;
            row[1] = request.getSender().getCustomer().getName();
            row[2] = request.getReceiver()== null ? null : request.getReceiver().getEmployee().getName();          
            row[3] = request.getMessage();
            row[4] = request.getStatus();
            LaundryWorkRequest laundryRequest=(LaundryWorkRequest)request;
            row[5]=laundryRequest.getResult();
            row[6]=request.getSender().getCustomer().getRoom().getRoomNo();
            
            model.addRow(row);
            }
        }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, "There is network issue", "Warning", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        assignJButton = new javax.swing.JButton();
        processJButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        laundryTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(null);

        assignJButton.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        assignJButton.setText("Assign to me");
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });
        add(assignJButton);
        assignJButton.setBounds(490, 590, 290, 37);

        processJButton.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        processJButton.setText("Process");
        processJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processJButtonActionPerformed(evt);
            }
        });
        add(processJButton);
        processJButton.setBounds(1020, 590, 250, 37);

        logoutButton.setFont(new java.awt.Font("Snap ITC", 2, 24)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(0, 102, 102));
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        add(logoutButton);
        logoutButton.setBounds(924, 16, 180, 41);

        laundryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Customer", "Attendant", "Message", "Status", "Comments", "Room No"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(laundryTable);

        add(jScrollPane3);
        jScrollPane3.setBounds(550, 220, 717, 281);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/marriott_logo_redBackground_187x86.gif"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 190, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/request.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1990, 1030);

        jLabel3.setText("jLabel3");
        add(jLabel3);
        jLabel3.setBounds(0, 0, 51, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed

        int selectedRow = laundryTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Select a request", "Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }

        WorkRequest request = (WorkRequest)laundryTable.getValueAt(selectedRow, 0);
        request.setReceiver(userAccount);
        request.setStatus("In Progress");
        JOptionPane.showMessageDialog(this, "This work is assigned to you", "Success", JOptionPane.WARNING_MESSAGE);
        populateTable();
    }//GEN-LAST:event_assignJButtonActionPerformed

    private void processJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processJButtonActionPerformed

        int selectedRow = laundryTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Select a request", "Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }

        LaundryWorkRequest request = (LaundryWorkRequest)laundryTable.getValueAt(selectedRow, 0);
        request.setStatus("Processing");

        ProcessLaundryRequestJPanel processWorkRequestJPanel = new ProcessLaundryRequestJPanel(userProcessContainer, request);
        userProcessContainer.add("ProcessLaundryRequestJPanel", processWorkRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_processJButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.removeAll();
        userProcessContainer.add(mainPanel);
    }//GEN-LAST:event_logoutButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable laundryTable;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton processJButton;
    // End of variables declaration//GEN-END:variables
}
