/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Cook;

import Business.Organization.CookOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FoodRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vidya
 */
public class CookWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CookWorkAreaJPanel
     */
    private CookOrganization cookOrganization;
    private JPanel userProcessContainer;
    private JPanel mainPanel;
    private UserAccount userAccount;
    public CookWorkAreaJPanel(JPanel userProcessContainer,UserAccount userAccount,Organization organization,JPanel mainPanel) {
        initComponents();
        cookOrganization=(CookOrganization)organization;
        this.userProcessContainer=userProcessContainer;
        this.mainPanel=mainPanel;
        this.userAccount=userAccount;
        populateTable();
    }

    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)foodRequestTable.getModel();
        
        model.setRowCount(0);
        try{
        for(WorkRequest request : cookOrganization.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[6];
            row[0] = request;
            row[1] = request.getMessage();
            row[2] = request.getSender().getCustomer().getName();
            row[3] = request.getReceiver()== null ? null : request.getReceiver().getEmployee().getName();          
            row[4] = request.getStatus();
            row[5]=request.getSender().getCustomer().getRoom().getRoomNo();
            model.addRow(row);
        }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,"There is network issue","Error", JOptionPane.WARNING_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        foodRequestTable = new javax.swing.JTable();
        processJButton = new javax.swing.JButton();
        assignJButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        foodRequestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Message", "Customer", "Cook", "Status", "Room No"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(foodRequestTable);

        add(jScrollPane3);
        jScrollPane3.setBounds(15, 163, 926, 266);

        processJButton.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        processJButton.setText("Process");
        processJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processJButtonActionPerformed(evt);
            }
        });
        add(processJButton);
        processJButton.setBounds(820, 650, 300, 37);

        assignJButton.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        assignJButton.setText("Assign to me");
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });
        add(assignJButton);
        assignJButton.setBounds(640, 530, 340, 37);

        logoutButton.setFont(new java.awt.Font("Snap ITC", 2, 24)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(0, 102, 102));
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        add(logoutButton);
        logoutButton.setBounds(743, 16, 180, 41);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/marriott_logo_redBackground_187x86.gif"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 190, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\vidya\\Desktop\\images\\request.jpg")); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 10, 1940, 1020);
    }// </editor-fold>//GEN-END:initComponents

    private void processJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processJButtonActionPerformed

        int selectedRow = foodRequestTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Select a row", "Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }

        FoodRequest request = (FoodRequest)foodRequestTable.getValueAt(selectedRow, 0);

        request.setStatus("Processing");

        ProcessRequestJPanel processWorkRequestJPanel = new ProcessRequestJPanel(userProcessContainer, request);
        userProcessContainer.add("processWorkRequestJPanel", processWorkRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_processJButtonActionPerformed

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed

        int selectedRow = foodRequestTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Select a row", "Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }

        WorkRequest request = (WorkRequest)foodRequestTable.getValueAt(selectedRow, 0);
        request.setReceiver(userAccount);
        request.setStatus("In Progress");
        JOptionPane.showMessageDialog(this, "This work is assigned to you", "Success", JOptionPane.WARNING_MESSAGE);
        populateTable();

    }//GEN-LAST:event_assignJButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.removeAll();
        userProcessContainer.add(mainPanel);
    }//GEN-LAST:event_logoutButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignJButton;
    private javax.swing.JTable foodRequestTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton processJButton;
    // End of variables declaration//GEN-END:variables
}
