/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Security;

import Business.Organization.Organization;
import Business.Organization.SecurityOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CarWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vidya
 */
public class SecurityWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SecurityWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private JPanel mainPanel;
    private UserAccount userAccount;
    private SecurityOrganization securityOrganization;
    public SecurityWorkAreaJPanel(JPanel userProcessContainer,UserAccount userAccount,Organization organization,JPanel mainPanel) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.userAccount=userAccount;
        this.mainPanel=mainPanel;
        securityOrganization=(SecurityOrganization)organization;
        populateTable();
    }

    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)carTable.getModel();
        
        model.setRowCount(0);
        try{
        for(WorkRequest request : securityOrganization.getWorkQueue().getWorkRequestList()){
            if(request instanceof CarWorkRequest){
            Object[] row = new Object[7];
            row[0] = request;
            row[1] = request.getSender().getCustomer().getName();
            row[2] = request.getReceiver()== null ? null : request.getReceiver().getEmployee().getName(); 
            row[3] = request.getMessage();
            row[4] = request.getStatus();
            CarWorkRequest carRequest=(CarWorkRequest)request;
            row[5]=carRequest.getResult();
            row[6]=request.getSender().getCustomer().getCarNo();
            model.addRow(row);
            }
        }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, "There is network issue", "Warning", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoutButton = new javax.swing.JButton();
        assignJButton = new javax.swing.JButton();
        processJButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        carTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        logoutButton.setFont(new java.awt.Font("Snap ITC", 2, 24)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(0, 102, 102));
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        add(logoutButton);
        logoutButton.setBounds(742, 65, 180, 41);

        assignJButton.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        assignJButton.setText("Assign to me");
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });
        add(assignJButton);
        assignJButton.setBounds(530, 570, 240, 37);

        processJButton.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        processJButton.setText("Process");
        processJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processJButtonActionPerformed(evt);
            }
        });
        add(processJButton);
        processJButton.setBounds(840, 570, 200, 37);

        carTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Customer", "Security Official", "Message", "Status", "Comments", "Car No"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(carTable);

        add(jScrollPane3);
        jScrollPane3.setBounds(74, 183, 781, 266);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/marriott_logo_redBackground_187x86.gif"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 190, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\vidya\\Desktop\\images\\request.jpg")); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1790, 1010);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.removeAll();
        userProcessContainer.add(mainPanel);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed

        int selectedRow = carTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Select a request", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        WorkRequest request = (WorkRequest)carTable.getValueAt(selectedRow, 0);
        request.setReceiver(userAccount);
        request.setStatus("In Progress");
        JOptionPane.showMessageDialog(this, "This work assigned to you ", "Success", JOptionPane.INFORMATION_MESSAGE);
        populateTable();
    }//GEN-LAST:event_assignJButtonActionPerformed

    private void processJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processJButtonActionPerformed

        int selectedRow = carTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Select a request", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        CarWorkRequest request = (CarWorkRequest)carTable.getValueAt(selectedRow, 0);

        request.setStatus("Processing");

        ProcessCarRequestJPanel processCarRequestJPanel = new ProcessCarRequestJPanel(userProcessContainer, request);
        userProcessContainer.add("ProcessCarRequestJPanel", processCarRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_processJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignJButton;
    private javax.swing.JTable carTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton processJButton;
    // End of variables declaration//GEN-END:variables
}
