/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Room;

import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.ManagerOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import UserInterface.Food.ViewMenuPanel;
import UserInterface.Manager.FireJPanel;
import com.twilio.sdk.TwilioRestClient;
import com.twilio.sdk.TwilioRestException;
import com.twilio.sdk.resource.factory.MessageFactory;
import com.twilio.sdk.resource.instance.Message;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.apache.http.NameValuePair;
import org.apache.http.message.BasicNameValuePair;

/**
 *
 * @author vidya
 */
public class RoomFacilityJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RoomFacilityJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    public RoomFacilityJPanel(JPanel userProcessContainer,UserAccount userAccount,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        this.userAccount=userAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        laundryButton = new javax.swing.JButton();
        emergencyReq = new javax.swing.JButton();
        cleaningReqButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        foodRequestButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        mesText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(null);

        laundryButton.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        laundryButton.setText("Laundry Request");
        laundryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laundryButtonActionPerformed(evt);
            }
        });
        add(laundryButton);
        laundryButton.setBounds(840, 550, 340, 37);

        emergencyReq.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        emergencyReq.setText("Emergency Request");
        emergencyReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergencyReqActionPerformed(evt);
            }
        });
        add(emergencyReq);
        emergencyReq.setBounds(1210, 680, 340, 37);

        cleaningReqButton.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        cleaningReqButton.setText("Cleaning Request");
        cleaningReqButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleaningReqButtonActionPerformed(evt);
            }
        });
        add(cleaningReqButton);
        cleaningReqButton.setBounds(840, 460, 340, 37);

        backJButton.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton);
        backJButton.setBounds(920, 810, 220, 37);

        foodRequestButton.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        foodRequestButton.setText("Food Request");
        foodRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodRequestButtonActionPerformed(evt);
            }
        });
        add(foodRequestButton);
        foodRequestButton.setBounds(840, 380, 340, 37);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/marriott_logo_redBackground_187x86.gif"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 190, 90);

        mesText.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        add(mesText);
        mesText.setBounds(850, 680, 320, 34);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("Message to the Manager");
        add(jLabel1);
        jLabel1.setBounds(590, 680, 260, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/request.jpg"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(0, 0, 1920, 900);
    }// </editor-fold>//GEN-END:initComponents

    private void emergencyReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emergencyReqActionPerformed
        // TODO add your handling code here:
        try{
        if(mesText.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please type in the message","Error", JOptionPane.WARNING_MESSAGE);
        }
        for(Organization organization:enterprise.getOrganizationDirectory().getOrganizationDirectory()){
            if(organization instanceof ManagerOrganization){
                for(Employee employee:organization.getEmployeeDirectory().getEmployeeDirectory()){
                    getMessage(employee.getPhoneNo());
                    JOptionPane.showMessageDialog(null,"Message sent to manager successfully","Success", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Missing out on important information","Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_emergencyReqActionPerformed

    private void getMessage(String phoneNo){
    try{  
    String ACCOUNT_SID = "AC2520cf90b14918a1552da17f70ad995f"; 
    String AUTH_TOKEN = "805dac7aa014c5a9e51cc24cf345767c";     
    TwilioRestClient client = new TwilioRestClient(ACCOUNT_SID, AUTH_TOKEN); 
 
   // Build the parameters 
   List<NameValuePair> params = new ArrayList<>(); 
   params.add(new BasicNameValuePair("To", "+1" + phoneNo)); 
   params.add(new BasicNameValuePair("From", "+18305496569")); 
   params.add(new BasicNameValuePair("Body", mesText.getText())); 
   
 
   MessageFactory messageFactory = client.getAccount().getMessageFactory(); 
   Message message; 
 
            message = messageFactory.create(params);
            System.out.println(message.getSid());
        } 
    catch (TwilioRestException ex) {
            Logger.getLogger(FireJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    catch(Exception ex){
        JOptionPane.showMessageDialog(this, "Please add phone no","Error",JOptionPane.ERROR_MESSAGE);
        
    }
    
    }
    
    private void cleaningReqButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleaningReqButtonActionPerformed
        // TODO add your handling code here:
       CleaningCustomerRequestJPanel cleaningPanel=new CleaningCustomerRequestJPanel(userProcessContainer, userAccount,enterprise);
       userProcessContainer.add("CleaningCustomerRequestJPanel",cleaningPanel);
       CardLayout layout = (CardLayout) userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_cleaningReqButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void laundryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laundryButtonActionPerformed
        // TODO add your handling code here:
       LaundryCustomerRequestJPanel cleaningPanel=new LaundryCustomerRequestJPanel(userProcessContainer, enterprise,userAccount);
       userProcessContainer.add("LaundryCustomerRequestJPanel",cleaningPanel);
       CardLayout layout = (CardLayout) userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_laundryButtonActionPerformed

    private void foodRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodRequestButtonActionPerformed
        // TODO add your handling code here:
        ViewMenuPanel viewPanel=new ViewMenuPanel(userProcessContainer, userAccount,enterprise);
        userProcessContainer.add("ViewMenuPanel",viewPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_foodRequestButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton cleaningReqButton;
    private javax.swing.JButton emergencyReq;
    private javax.swing.JButton foodRequestButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton laundryButton;
    private javax.swing.JTextField mesText;
    // End of variables declaration//GEN-END:variables
}
