/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Manager;

import Business.UserAccount.UserAccount;
import com.twilio.sdk.TwilioRestClient;
import com.twilio.sdk.TwilioRestException;
import com.twilio.sdk.resource.factory.MessageFactory;
import com.twilio.sdk.resource.instance.Message;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;
import org.apache.http.NameValuePair;
import org.apache.http.message.BasicNameValuePair;

/**
 *
 * @author vidya
 */
public class FireJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FireJPanel
     */
    private JPanel userProcessContainer;
    private int fireThresold;
    private UserAccount userAccount;
    private static int lastValue=0;
    public FireJPanel(JPanel userProcessContainer,int fireThresold,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.fireThresold=fireThresold;
        this.userAccount=userAccount;
        
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        monitorButton = new javax.swing.JButton();
        fireText = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        monitorButton.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        monitorButton.setText("Start Monitoring Heat Level");
        monitorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monitorButtonActionPerformed(evt);
            }
        });
        add(monitorButton);
        monitorButton.setBounds(170, 125, 315, 37);

        fireText.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        fireText.setForeground(new java.awt.Color(255, 255, 255));
        add(fireText);
        fireText.setBounds(540, 110, 225, 67);

        backJButton.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton);
        backJButton.setBounds(102, 352, 170, 37);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/marriott_logo_redBackground_187x86.gif"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 190, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/manager1.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1530, 900);
    }// </editor-fold>//GEN-END:initComponents

    private void monitorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monitorButtonActionPerformed
        // TODO add your handling code here:
        
    populateHeatLevel();
    }//GEN-LAST:event_monitorButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed
  
    public void populateHeatLevel(){
       
        new Timer(1000, new ActionListener(){
            Random random=new Random();
            int counter=0;
            @Override
            public void actionPerformed(ActionEvent ae) {
                counter=random.nextInt(20);
                fireText.setText(String.valueOf(counter));
                if(counter>=fireThresold){
                   getMessage();
                    ((Timer)ae.getSource()).stop();
                }
            }
        }).start();
    
    }
    private void getMessage(){
    try{  
    String ACCOUNT_SID = "AC2520cf90b14918a1552da17f70ad995f"; 
    String AUTH_TOKEN = "805dac7aa014c5a9e51cc24cf345767c";     
    TwilioRestClient client = new TwilioRestClient(ACCOUNT_SID, AUTH_TOKEN); 
 
   // Build the parameters 
   List<NameValuePair> params = new ArrayList<>(); 
   params.add(new BasicNameValuePair("To", "+1" + userAccount.getEmployee().getPhoneNo())); 
   params.add(new BasicNameValuePair("From", "+18305496569")); 
   params.add(new BasicNameValuePair("Body", "Hey !!! Please rescue.. Fire at Marriott....")); 
   
 
   MessageFactory messageFactory = client.getAccount().getMessageFactory(); 
   Message message; 
 
            message = messageFactory.create(params);
            System.out.println(message.getSid());
        } 
    catch (TwilioRestException ex) {
            Logger.getLogger(FireJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    catch(Exception ex){
        JOptionPane.showMessageDialog(this, "Please add phone no","Error",JOptionPane.ERROR_MESSAGE);
        
    }
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel fireText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton monitorButton;
    // End of variables declaration//GEN-END:variables
}
