/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminWorkArea;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import UserInterface.MainJFrame;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author vidya
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    private EcoSystem system;
    private JPanel userProcessContainer;
    private JPanel mainPanel;
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer,EcoSystem system,JPanel mainPanel) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.system=system;
        this.mainPanel=mainPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageNetworkButton = new javax.swing.JButton();
        manageEnterpriseButton = new javax.swing.JButton();
        manageOrganizationButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        manageNetworkButton.setBackground(new java.awt.Color(0, 102, 51));
        manageNetworkButton.setFont(new java.awt.Font("Snap ITC", 2, 24)); // NOI18N
        manageNetworkButton.setForeground(new java.awt.Color(255, 153, 51));
        manageNetworkButton.setText("Manage Network");
        manageNetworkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageNetworkButtonActionPerformed(evt);
            }
        });
        add(manageNetworkButton);
        manageNetworkButton.setBounds(130, 210, 360, 41);

        manageEnterpriseButton.setBackground(new java.awt.Color(0, 102, 51));
        manageEnterpriseButton.setFont(new java.awt.Font("Snap ITC", 2, 24)); // NOI18N
        manageEnterpriseButton.setForeground(new java.awt.Color(255, 153, 51));
        manageEnterpriseButton.setText("Manage Enterprise");
        manageEnterpriseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseButtonActionPerformed(evt);
            }
        });
        add(manageEnterpriseButton);
        manageEnterpriseButton.setBounds(400, 310, 410, 41);

        manageOrganizationButton.setBackground(new java.awt.Color(0, 102, 51));
        manageOrganizationButton.setFont(new java.awt.Font("Snap ITC", 2, 24)); // NOI18N
        manageOrganizationButton.setForeground(new java.awt.Color(255, 153, 51));
        manageOrganizationButton.setText("Manage Enterprise Admin");
        manageOrganizationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationButtonActionPerformed(evt);
            }
        });
        add(manageOrganizationButton);
        manageOrganizationButton.setBounds(660, 410, 430, 41);

        logoutButton.setFont(new java.awt.Font("Snap ITC", 2, 24)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(0, 102, 102));
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        add(logoutButton);
        logoutButton.setBounds(1430, 150, 180, 41);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/marriott_logo_redBackground_187x86.gif"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, 10, 190, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Bangkok-lobby.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 10, 1950, 850);
    }// </editor-fold>//GEN-END:initComponents

    private void manageNetworkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageNetworkButtonActionPerformed
        // TODO add your handling code here:
        ManageNetworkPanel manageNetwork= new ManageNetworkPanel(userProcessContainer,system);
        userProcessContainer.add("manageNetwork",manageNetwork);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageNetworkButtonActionPerformed

    private void manageEnterpriseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseButtonActionPerformed
        // TODO add your handling code here:
        ManageEnterprisePanel manageEnterprise= new ManageEnterprisePanel(userProcessContainer,system);
        userProcessContainer.add("manageEnterprise",manageEnterprise);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEnterpriseButtonActionPerformed

    private void manageOrganizationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationButtonActionPerformed
        // TODO add your handling code here:
        ManageEnterpriseAdminPanel manageEnterpriseAdmin= new ManageEnterpriseAdminPanel(userProcessContainer,system);
        userProcessContainer.add("ManageEnterpriseAdminPanel",manageEnterpriseAdmin);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrganizationButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.removeAll();
        userProcessContainer.add(mainPanel);
    }//GEN-LAST:event_logoutButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton manageEnterpriseButton;
    private javax.swing.JButton manageNetworkButton;
    private javax.swing.JButton manageOrganizationButton;
    // End of variables declaration//GEN-END:variables
}
