/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;

import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author vidya
 */
public class AddDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddDetailsJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    public AddDetailsJPanel(JPanel userProcessContainer,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.userAccount=userAccount;
        populateCardTypeCombo();
    }
    
    private void populateCardTypeCombo(){
        paymentTypeCombo.removeAllItems();
        paymentTypeCombo.addItem("Apple Pay");
        paymentTypeCombo.addItem("Google");       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        phoneText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addressText = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        carNoText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        paymentTypeCombo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setLayout(null);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Phone No");
        add(jLabel3);
        jLabel3.setBounds(1110, 260, 130, 20);

        phoneText.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        phoneText.setForeground(new java.awt.Color(0, 0, 51));
        phoneText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneTextKeyTyped(evt);
            }
        });
        add(phoneText);
        phoneText.setBounds(1260, 260, 203, 26);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Address");
        add(jLabel4);
        jLabel4.setBounds(1110, 330, 130, 30);

        addressText.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        addressText.setForeground(new java.awt.Color(0, 0, 51));
        add(addressText);
        addressText.setBounds(1260, 330, 203, 30);

        addButton.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        addButton.setForeground(new java.awt.Color(0, 0, 51));
        addButton.setText("Add Details");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        add(addButton);
        addButton.setBounds(1200, 720, 250, 29);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("Payment Details");
        add(jLabel5);
        jLabel5.setBounds(1160, 490, 280, 33);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Please fill in the Details:");
        add(jLabel1);
        jLabel1.setBounds(1120, 140, 350, 33);

        backJButton.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        backJButton.setForeground(new java.awt.Color(0, 0, 51));
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton);
        backJButton.setBounds(1010, 720, 140, 29);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 51));
        jLabel9.setText("Car No");
        add(jLabel9);
        jLabel9.setBounds(1110, 420, 89, 20);

        carNoText.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        carNoText.setForeground(new java.awt.Color(0, 0, 51));
        carNoText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                carNoTextKeyTyped(evt);
            }
        });
        add(carNoText);
        carNoText.setBounds(1270, 420, 203, 26);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/marriott_logo_redBackground_187x86.gif"))); // NOI18N
        jLabel10.setText("jLabel2");
        add(jLabel10);
        jLabel10.setBounds(0, 0, 190, 90);

        paymentTypeCombo.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        paymentTypeCombo.setForeground(new java.awt.Color(0, 0, 51));
        paymentTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(paymentTypeCombo);
        paymentTypeCombo.setBounds(1340, 580, 220, 40);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Payment Type(Apple Pay or Google Wallet )");
        add(jLabel2);
        jLabel2.setBounds(800, 580, 530, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/customer1.jpg"))); // NOI18N
        add(jLabel6);
        jLabel6.setBounds(0, 0, 1890, 1080);
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        
        String address=addressText.getText();
        String phoneNo=phoneText.getText();
        String carNo=carNoText.getText();
        String paymentType=paymentTypeCombo.getSelectedItem().toString();
        if(address.isEmpty() || phoneNo.isEmpty() || carNo.isEmpty() || paymentType==null){
            JOptionPane.showMessageDialog(null,"Please fill in all the details","Error", JOptionPane.WARNING_MESSAGE);
            return;
        }   
        
        if(phoneNo.length()!=10){
            JOptionPane.showMessageDialog(null,"Please fill in valid details","Error", JOptionPane.WARNING_MESSAGE); 
            return;
        }
        userAccount.getCustomer().setAddress(address);
        userAccount.getCustomer().setPhoneNo(phoneNo);
        userAccount.getCustomer().setPaymentType(paymentType);
        userAccount.getCustomer().setCarNo(carNo);
        JOptionPane.showMessageDialog(null,"Details added succesfully","Success", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backJButtonActionPerformed

    private void phoneTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneTextKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_phoneTextKeyTyped

    private void carNoTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_carNoTextKeyTyped
        // TODO add your handling code here:
        if(!(Character.isDigit(evt.getKeyChar())) || (!Character.isLetter(evt.getKeyChar()))){
            evt.consume();
        }
    }//GEN-LAST:event_carNoTextKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField addressText;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField carNoText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox paymentTypeCombo;
    private javax.swing.JTextField phoneText;
    // End of variables declaration//GEN-END:variables
}
