/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;

import Business.Customer.Customer;
import Business.Food.FoodMenuItem;
import Business.Food.FoodOrder;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vidya
 */
public class PaymentPanel extends javax.swing.JPanel {

    /**
     * Creates new form PaymentPanel
     */
    private JPanel userProcessContainer;
    private Customer customer;
    private double foodBill=0;
    public PaymentPanel(JPanel userProcessContainer,Customer customer) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.customer=customer;
        foodBill=calculateFoodBill();
        noOfdaysText.setText(String.valueOf(customer.getNoOfDays()));
        foodText.setText(String.valueOf(foodBill));
        roomBillText.setText(String.valueOf(customer.getRoomBill()));
        String totalBill= String.valueOf(foodBill+customer.getRoomBill());
        totalBillText.setText(totalBill);
        populateTable();
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        totalBillText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        foodTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        noOfdaysText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        roomBillText = new javax.swing.JTextField();
        foodText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Bill Details");
        add(jLabel1);
        jLabel1.setBounds(710, 40, 170, 33);

        totalBillText.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        add(totalBillText);
        totalBillText.setBounds(230, 170, 130, 30);

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Total Bill");
        add(jLabel2);
        jLabel2.setBounds(70, 170, 130, 33);

        backJButton.setBackground(new java.awt.Color(204, 204, 255));
        backJButton.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        backJButton.setForeground(new java.awt.Color(0, 0, 204));
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton);
        backJButton.setBounds(130, 230, 190, 41);

        foodTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Food Item", "Price", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(foodTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 360, 442, 350);

        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Food Bill");
        add(jLabel5);
        jLabel5.setBounds(74, 102, 160, 33);

        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("No Of Days");
        add(jLabel4);
        jLabel4.setBounds(1200, 110, 180, 33);

        noOfdaysText.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        add(noOfdaysText);
        noOfdaysText.setBounds(1390, 110, 169, 30);

        jLabel6.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Room Bill");
        add(jLabel6);
        jLabel6.setBounds(1180, 230, 170, 30);

        roomBillText.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        add(roomBillText);
        roomBillText.setBounds(1380, 230, 169, 30);

        foodText.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        add(foodText);
        foodText.setBounds(230, 100, 130, 32);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/marriott_logo_redBackground_187x86.gif"))); // NOI18N
        jLabel3.setText("jLabel2");
        add(jLabel3);
        jLabel3.setBounds(0, 0, 190, 90);
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private double calculateFoodBill(){
      
     if(customer.getOrderList()!=null){ 
      for(FoodOrder foodOrder: customer.getOrderList().getMasterList()){
          for(FoodMenuItem foodMenuItem:foodOrder.getFoodOrderList()){
              foodBill=foodBill+foodMenuItem.getPrice()*foodMenuItem.getQuantity();
              
          }
      }
     }
      return foodBill;
    }
    
   
    
    

    private void populateTable(){
        DefaultTableModel model=(DefaultTableModel)foodTable.getModel();
        model.setRowCount(0);
        for(FoodOrder foodOrder: customer.getOrderList().getMasterList()){
          for(FoodMenuItem foodMenuItem:foodOrder.getFoodOrderList()){
              Object[] row=new Object[3];
             row[0]=foodMenuItem.getName();
             row[1]=foodMenuItem.getPrice();
             row[2]=foodMenuItem.getQuantity();
             model.addRow(row);
          }
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTable foodTable;
    private javax.swing.JTextField foodText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField noOfdaysText;
    private javax.swing.JTextField roomBillText;
    private javax.swing.JTextField totalBillText;
    // End of variables declaration//GEN-END:variables
}
