/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;

import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author vidya
 */
public class ViewDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewDetailsJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    public ViewDetailsJPanel(JPanel userProcessContainer,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.userAccount=userAccount;
        populateCardTypeCombo();
        populateData();
    }
    
    private void populateData(){
        phoneText.setText(userAccount.getCustomer().getPhoneNo());
        addressText.setText(userAccount.getCustomer().getAddress());
        carNoText.setText(userAccount.getCustomer().getCarNo());
        paymentTypeCombo.setSelectedItem(userAccount.getCustomer().getPaymentType());
    }

    private void populateCardTypeCombo(){
        paymentTypeCombo.removeAllItems();
        paymentTypeCombo.addItem("Apple Pay");
        paymentTypeCombo.addItem("Google");       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        phoneText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addressText = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        paymentTypeCombo = new javax.swing.JComboBox();
        carNoText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setLayout(null);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel3.setText("Phone No");
        add(jLabel3);
        jLabel3.setBounds(1090, 260, 104, 29);

        phoneText.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        phoneText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneTextKeyTyped(evt);
            }
        });
        add(phoneText);
        phoneText.setBounds(1290, 260, 203, 35);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel4.setText("Address");
        add(jLabel4);
        jLabel4.setBounds(1090, 330, 89, 29);

        addressText.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        add(addressText);
        addressText.setBounds(1290, 330, 203, 35);

        updateButton.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        updateButton.setText("Update Details");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        add(updateButton);
        updateButton.setBounds(1260, 680, 210, 37);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel5.setText("Payment Details");
        add(jLabel5);
        jLabel5.setBounds(1090, 460, 260, 33);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel1.setText("Please fill in the Details:");
        add(jLabel1);
        jLabel1.setBounds(1120, 170, 520, 33);

        backJButton.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton);
        backJButton.setBounds(1000, 680, 113, 37);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/marriott_logo_redBackground_187x86.gif"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 190, 90);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel6.setText("Please select a payment type");
        add(jLabel6);
        jLabel6.setBounds(880, 540, 334, 29);

        paymentTypeCombo.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        paymentTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        paymentTypeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentTypeComboActionPerformed(evt);
            }
        });
        add(paymentTypeCombo);
        paymentTypeCombo.setBounds(1300, 530, 190, 35);

        carNoText.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        carNoText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                carNoTextKeyTyped(evt);
            }
        });
        add(carNoText);
        carNoText.setBounds(1290, 400, 203, 35);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel9.setText("Car No");
        add(jLabel9);
        jLabel9.setBounds(1090, 400, 89, 29);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\vidya\\Desktop\\images\\customer1.jpg")); // NOI18N
        add(jLabel7);
        jLabel7.setBounds(0, 0, 1920, 940);
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        try{
        String address=addressText.getText();
        String phoneNo=phoneText.getText();
        String paymentType=paymentTypeCombo.getSelectedItem().toString();
        String carNo=carNoText.getText();
        if(address.isEmpty() || phoneNo.isEmpty() || carNo.isEmpty() || paymentType.isEmpty()){
            JOptionPane.showMessageDialog(null,"Please fill in all the details","Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(phoneNo.length()!=10){
            JOptionPane.showMessageDialog(null,"Please fill in valid details","Error", JOptionPane.WARNING_MESSAGE); 
            return;
        }

        userAccount.getCustomer().setAddress(address);
        userAccount.getCustomer().setPhoneNo(phoneNo);
        userAccount.getCustomer().setPaymentType(paymentType);
        JOptionPane.showMessageDialog(null,"Details added succesfully","Success", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception ex){
             JOptionPane.showMessageDialog(null,"Please fill in valid details","Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backJButtonActionPerformed

    private void carNoTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_carNoTextKeyTyped
        // TODO add your handling code here:
        if(!(Character.isDigit(evt.getKeyChar())) || (!Character.isLetter(evt.getKeyChar()))){
            evt.consume();
        }
    }//GEN-LAST:event_carNoTextKeyTyped

    private void paymentTypeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentTypeComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentTypeComboActionPerformed

    private void phoneTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneTextKeyTyped
        // TODO add your handling code here:
        if(!(Character.isDigit(evt.getKeyChar()))){
            evt.consume();
        }
    }//GEN-LAST:event_phoneTextKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressText;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField carNoText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox paymentTypeCombo;
    private javax.swing.JTextField phoneText;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
